# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('count', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sku', models.PositiveIntegerField(unique=True)),
                ('vintage', models.PositiveSmallIntegerField(null=True)),
                ('winery', models.CharField(max_length=128, null=True)),
                ('country', models.CharField(max_length=128, null=True)),
                ('region', models.CharField(max_length=128, null=True)),
                ('appellation', models.CharField(max_length=128, null=True)),
                ('varietal', models.CharField(max_length=128, null=True)),
                ('wine_type', models.CharField(max_length=128, null=True)),
                ('description', models.CharField(max_length=2048, null=True)),
                ('JH', models.PositiveSmallIntegerField(null=True, verbose_name='James Halliday')),
                ('JS', models.PositiveSmallIntegerField(null=True, verbose_name='James Suckling')),
                ('RP', models.PositiveSmallIntegerField(null=True, verbose_name='Robert Parker')),
                ('ST', models.PositiveSmallIntegerField(null=True, verbose_name='Stephen Tanzer')),
                ('AG', models.PositiveSmallIntegerField(null=True, verbose_name='Antonio Galloni')),
                ('D', models.PositiveSmallIntegerField(null=True, verbose_name='Decanter')),
                ('WA', models.PositiveSmallIntegerField(null=True, verbose_name='Wine Advocate')),
                ('WE', models.PositiveSmallIntegerField(null=True, verbose_name='Wine Enthusiast')),
                ('WS', models.PositiveSmallIntegerField(null=True, verbose_name='Wine Spectator')),
                ('WandS', models.PositiveSmallIntegerField(null=True, verbose_name='Wine & Spirits')),
                ('WW', models.PositiveSmallIntegerField(null=True, verbose_name='Wilfred Wong')),
            ],
        ),
    ]
